.\" Man page for lsiommu
.TH lsiommu 1 "July 2025" "lsiommu 1.0" "User Commands"
.SH NAME
lsiommu \- list all IOMMU groups
.SH SYNOPSIS
.B lsiommu
[\-\-format \fIformat\fP]
[\-h|\-\-help]
.SH DESCRIPTION
.B lsiommu
is a command-line tool for Linux that lists IOMMU groups and PCI
devices. The output is by default plain text but can be optionally set
to JSON. `lsiommu` can be compile-time selected to discover devices
either from
.BR udev (7)
(the default) or
.BR sysfs (5).
.PP
Groups are sorted by their numeric ID, and devices within each group
are sorted by their PCI address.
.SH OPTIONS
.TP
.B \-\-format \fIformat\fP
Set the output format. Supported formats are \fBplain\fP (default) and \fBjson\fP.
.TP
.B \-h, \--help
Print help and exit.
.SH SEE ALSO
.BR udev (7),
.BR libudev (3),
.BR sysfs (5)
.SH AUTHOR
Jarkko Sakkinen 2025
