.\" Man page for lsiommu
.TH lsiommu 1 "July 2025" "lsiommu 1.0" "User Commands"
.SH NAME
lsiommu \- list all IOMMU groups
.SH SYNOPSIS
.B lsiommu
[\-\-style \fIstyle\fP]
[\-h|\-\-help]
.SH DESCRIPTION
.B lsiommu
lists all IOMMU groups and their associated PCI devices. By default, it uses the
.BR libudev (3)
library to discover hardware, query device properties, and determine IOMMU groupings. This can be changed to a manual
.BR sysfs (5)
filesystem scan at compile-time.
.PP
Groups are sorted by their numeric ID, and devices within each group are sorted by their PCI address.
.SH OPTIONS
.TP
.B \-\-style \fIstyle\fP
Set the output style. Supported styles are \fBplain\fP (default) and \fBjson\fP.
.TP
.B \-h, \--help
Print help and exit.
.SH SEE ALSO
.BR udev (7),
.BR libudev (3),
.BR sysfs (5)
.SH AUTHOR
Jarkko Sakkinen 2025
